### ISSUE TITLE
Neleze se přihlásit do stravy

### ISSUE THREAD

**Issue by PanJohnny** [vojta-dev/popelari#1]
Ahoj i když vyplním správně údaje nefunguje přihlašování.

![Screenshot_20230430-091639.jpg](https://user-images.githubusercontent.com/67548122/235340849-23d0a526-4421-470c-9ed9-ef11d918747d.jpg)

**Comment by voytxt** [comment]
Předpokládám, že tohle je v0.0.2 apk z releases, a že po kliknutí na sign in to ukáže "your credentials are incorrect" (pokud je to jinak, oprav mě).

U mé jídelny to funguje bez problémů, takže si myslím, že rozdíl bude ve verzi backendu, co školy používají (bolest). Například se mi pro vaši jídelnu nepodařilo zobrazit `https://www.strava.cz/foxisapi/foxisapi.dll/istravne.istravne.process?xmljidelnickyA&zarizeni=0837` (píše to "Uživatel se přihlašuje k neznámému zařízení (jídelně). Jeho přihlášení je zamítnuto.") - pokud se ti to povede, tak napiš.

Pokud chceš, tak se tam můžeš zkusit přihlásit k testovací jídelně 0000 (jméno a heslo taky 0000), jen ať si můžeme být jistí, že ten problém netkví někde jinde.

**Comment by PanJohnny** [comment]
![Screenshot_20230430-113010.jpg](https://user-images.githubusercontent.com/67548122/235345997-7560e59a-8d7b-4a5e-81ba-6c3f99a48030.jpg)

0000 taky nefunkční, stáhnul jsem si poslední release

**Comment by PanJohnny** [comment]
**Hardware**: Samsung S7
**Verze androidu**: 9

Tady máš nějaký technický informace

**Comment by voytxt** [comment]
Nemáš u username náhodou mezeru na začátku? Jsem si myslel, že Flutter automaticky mezery na krajích oddělává, ale tak asi ne.

**Comment by PanJohnny** [comment]
Jo měl jsem u tý 0000 špatný username. Ale tvoje appka fakt nefunguje s mojí stravou.

Až budu doma tak se na to podívám. Třeba na něco přijdu a přihodím pull request.

**Comment by PanJohnny** [comment]
Jídelníček bez loginu už existuje a to: https://aplikace.strava.cz/tisk/jidelnicek

Nemůžu přijít na to proč mi nefunguje ta autorizace, teď jsem se koukal a https://aplikace.strava.cz má stejnej auth flow u mojí jídelny jako se kterým počítáš.

**Comment by voytxt** [comment]
Však v pohodě, až někdy budu mít čas a chuť, tak na to mrknu.

Jo a děkuju za ten odkaz na jídelníček bez loginu. :+1:

**Comment by PanJohnny** [comment]
Chuť není 😂. Tak zavírám

**Comment by voytxt** [comment]
Promiň 😅
